### ISSUE TITLE
Missing details about  `multiple` and `MM_hasUidField`

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#1054]
### Current behavior

Using the `multiple` option in mm select fields states that the boolean option `MM_hasUidField` has to be enabled and that "**you must ... include a UID field**", it's just not explained how to do it.

### Expected behavior/output

A clear description how to fulfill the requirements to use the `multiple` feature in combination with mm connections for select fields correctly.

### Links

[Option `multiple`](https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/CommonProperties/Multiple.html)
[Option `MM_hasUidField`](https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Group/Properties/Mm.html#columns-group-properties-mm-hasuidfield)

[StackOverflow Issue where these settings might be cause of problems](https://stackoverflow.com/questions/78518271/typo3-extbase-extension-with-bidirectional-mm-relation-messed-up-language-relati)

### TYPO3 versions

11

**Comment by DavidBruchmann** [comment]
@lolli42 perhaps you can shine a light on this topic?

**Comment by DavidBruchmann** [comment]
for TYPO3 v13 I'm aware that `MM_hasUidField` is [deprecated and not used anymore](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Deprecation-101554-ObsoleteTCAMM_hasUidField.html).

**Comment by garvinhicking** [comment]
Forge Ticket:

https://forge.typo3.org/issues/103604

MM_hasUidfield already documented here:

Type "select":
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Select/Properties/Mm.html#confval-mm-hasuidfield-type-select

Type "group":
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Group/Index.html#confval-group-mm-hasuidfield

It's missing here:

Type "inline":
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Inline/Index.html#confval-inline-mm-hasuidfield
(it's empty here)

Type "category":
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Category/Index.html#confval-category-mm

We need to add this to 11.5 and 12.4 that the field is required in those four types, and maybe directly add a note that it will no longer be needed starting with TYPO3v13.

I hope to find some time to do a PR for this, but help appreciated :)

**Comment by garvinhicking** [comment]
@linawolf That would be much appreciated - I'll probably only find time for it spontaneously during next 2 weeks of vacation 😅

**Comment by linawolf** [comment]
Whereever property multiple is mentioned we mention in both TYPO3 v11 and 12 that MM_hasUidfield is required. Wherever MM_hasUidfield  is explained we mention that it is required for multiple. It is also  So in my eyes this is resoved. It is also mentioned in TYPO3 13 that it is not needed anymore. So I think, this is resolved

**Comment by garvinhicking** [comment]
![image](https://github.com/user-attachments/assets/045be4b3-4198-48ff-977c-92f997c3a791)

Here is a bug though

**Comment by linawolf** [comment]
Done
