### ISSUE TITLE
TCA option appearance missing in type group

### ISSUE THREAD

**Issue by nhovratov** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#1162]
main/v12: https://docs.typo3.org/m/typo3/reference-tca/main/en-us//ColumnsConfig/Type/Group/Index.html
v11: https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Group/Properties/Appearance.html#appearance

Old link was `<t3tca:columns-group-properties-appearance>`

**Comment by froemken** [comment]
The option "appearance" has been removed with this patch:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/731/files

It's related to TYPO3 patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79400
which also @nhovratov has reviewed.

In TcaMigration I found following:
```
                unset(
                    $fieldConfig['config']['appearance']['elementBrowserType'],
                    $fieldConfig['config']['appearance']['elementBrowserAllowed']
                );

                // Also unset "appearance" if empty
                if (empty($fieldConfig['config']['appearance'])) {
                    unset($fieldConfig['config']['appearance']);
                }
```

Yes, seems that this option has been removed.

**Comment by nhovratov** [comment]
@froemken Ok, thanks for digging that out!
