### ISSUE TITLE
PR 145 needs to be backported to branches <= 7.6

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#147]
This PR was merged into 'latest (=8.7)'
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/145 

It should be applied to the older branches as well.

**Comment by lolli42** [comment]
Since 7.6 is in security bugfix mode only and used in legacy projects which didn't update yet but (hopefully) not for new projects anymore, i hope it is ok to just leave out this bugfix in 7.6 documentation branch. I'll close the issue.
