### ISSUE TITLE
Whats about Chapter "Additional TCA features"?

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#151]
In Version 8 the whole chapter "Additional TCA features" is dropped, is there any reason?
Concerning the new kind of building TYPO3\CMS\Backend\Form on Base of NodeFactory there is some info missing then, if someone is not switching between the versions.

**Comment by lolli42** [comment]
The 'additional tca features' contained only doc parts which are gone in v8
