### ISSUE TITLE
fieldControl is documented by mistake for on type="select"

### ISSUE THREAD

**Issue by dogawaf** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#160]
Hello

In the doc (https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Select.html#fieldcontrol) it is specified that we can use fieldControl on a type="select" field.
But in fact fieldControl is only support for type="group".

**Comment by lolli42** [comment]
fieldControl is only available for renderTypes multipleSideBySide and singleBox - I'll adapt docs accordingly.
