### ISSUE TITLE
Should versions 8-dev, 6.1 and 6.0 be rendered?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#174]
IMHO it would be better to not have them in the versions menu and possibly redirect the URLs. 
![tca](https://user-images.githubusercontent.com/13206455/38141007-b0aef3c6-3436-11e8-9c9c-5bcd0122fc70.png)

**Comment by DavidBruchmann** [comment]
Concerning the latest dev-Version that's not a good idea I think as it's presenting the current state. Consider that there are several active branches too.

**Comment by DavidBruchmann** [comment]
Concerning old versions it's quite useful having a reference if having to deal with old versions, and that's happening no too seldom. Just had to deal with TYPO3 3.5 and 3.8 but could manage never having the old docs on the site you posted ;-)

**Comment by sypets** [comment]
@DavidBruchmann Thanks for bringing this up. 

I meant the latest (9-dev) should definitiely be kept, as in:
* latest (9-dev)
* 8.7
* 7.6
* 6.2
* etc.

"latest 9-dev" is currently not displayed, in my opinion this is an error which I already reported.

"8-dev" makes no sense because the latest 8 is displayed as 8.7 (if I'm not mistaken).

Ok, I looked at the" Core API" docs and there also 6.1 and 6.0 are  displayed. 

Actually in my opinion I would do it the following way, but that's just my opinion:

For every major version (8, 7), only the latest minor should be displayed (latest=9, 8.7, 7.6). 

For example, if you are working on 6.1 you really should update to 6.2. So I don't see much advantage in keeping documentation for 6.1. Are there really people still using 6.0 or 6.1??? 

Perhaps I should state my motivations:

- It's enough work keeping the latest docs up to date
- Maintaining docs for older versions that are in no way maintained whatsoever (even as ELTS) is not something people will want to do.
- Updating a major version may be a huge problem for some sites. But updating to the latest release of a major version should not (I hope)
- I'm not even sure the docs for 6.0, 6.1 and 6.2 are even different so this discussion may actually be purely academic 

I agree, that it's useful to have docs available for older versions, but how far back and if preliminary versions should also be maintained is highly debatable. 

But my opinion is not "official" and I may change it in favor of better arguments. Actually I do see your point but I regard maintaining docs in an increasing number of different versions as not feasible.

The question is:

- do the docs for 6.0, 6.1 and 6.2 actually differ?
- Are the docs for 6.0 and 6.1 in a final state so they do not require maintainance?

**Comment by sypets** [comment]
To answer my own question: Yes there are differences in the 6.0, 6.1 and 6.2 branches. Some differences seem to be enhancements though not related to the version update.

**Comment by DavidBruchmann** [comment]
Hi Sybille,

"Are there really people still using 6.0 or 6.1???"
Yes, and some even 4.5 or 4.7 and I even searched some things for 3.5 and 3.8 related to the old versions of the extension [t3quotes](https://github.com/DavidBruchmann/t3quotes).
And there are still more extensions like that, so required versions beside documentation are not always related to existing websites.

"Maintaining docs .."
It there any (or much) work with maintenance of old docs?

"I'm not even sure the docs for 6.0, 6.1 and 6.2 are even different "
I don't know now related to TCA but in general these versions are quite different.
If you want to know exactly run a diff over the documents ...

I don't mind to hide old dev-versions but think they still should be archived somewhere.
In general it's still possible to find very old staff of TYPO3, but some things need a bit longer for being found as not everything is archived centralized. Sourceforge still has very old sites, but I had to find a private hosted copy of an old sourceforge-page to find the links - so the ways are sometimes strange.

I'm not officially involved in publishing the docs (neither hiding ;-) ), so I don't know what will be decided.

In general your proposition never might be bad to limit the amount of docs a bit, so don't regard me as useless collector ;-) but sometimes I still crawl in the old staff.

**Comment by DavidBruchmann** [comment]
I never expect anyone still to work on docs for version 6.
Any work can be only related to create / publish the old things in another kind (not as swx-files). But it seems those things are done already too.

**Comment by sypets** [comment]
Yes I _did_ run a diff over the documentation for 6.0 / 6.1 and 6.2 and they _are_ different. 

Thanks for your input. I think I'll close this issue. I thought it was a good idea when I opened it, but I think for now you've got me convinced and I think it is too much hassle to open up a discussion about it. 

Thanks again. :)
