### ISSUE TITLE
Use "nicely styled" parameter lists (e.g. AllowLanguageSynchronization) for other properties

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#177]
Example: https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Check.html?highlight=rendertype#allowlanguagesynchronization

see 
""nicely styled" of parameter lists
https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/DefinitionLists/Index.html

![allowlanguagesynchronization](https://user-images.githubusercontent.com/13206455/38491710-fa77a026-3bec-11e8-9d21-55d251b48b22.png)

**Comment by lolli42** [comment]
We'll not do that at the moment and use the "aspect" based layout for now: We still didn't get rid of the old table layout in all main documents, so for consistency we should first get that done. There are also some open questions regarding coloring and nesting of definition lists that need to be sorted out, first.
