### ISSUE TITLE
Add additional subheaders for properties (values, default, requirements)

### ISSUE THREAD

**Issue by gittyshittybangbang** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#194]
The TCA docs are quite extensive and often helpful, but a little hard to read in some places.

Would adding some extra headers in a consistent way be more helpful? I can add a PR, but wanted to get a second opinion first. 

Currently, you have _Datatype_, _Scope_, _Description_ and sometimes Default.

You could add:

* _Required_ (only if field is required)
* _Default_ (more often, often the default is just mentioned in the description)
* _Values_  (list possible values)
* _Requirements_ (or name it _Prerequisites_)
* _Example_ (as already used in [some places](https://docs.typo3.org/typo3cms/TCAReference/7.6/Reference/Columns/Inline/Index.html#foreign-selector-fieldtcaoverride), but more often not)

That way you won't have this information someplace in the description which is sometimes quite long. This information would be easier to spot quickly. 

Example: [suggestOptions](https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Group.html#suggestoptions)

Here, you could have:

* _Requirements_:
  * internal_type='db'
  * hideSuggest = False
* _Values_:
  * additionalSearchFields
  * addWhere 
  * ...

**Comment by nofreebielancer** [comment]
Related: #81

**Comment by linawolf** [comment]
I think I have worked in many of these suggestions already in the TCA overhaul
