### ISSUE TITLE
eval / custom class example with class path as string does not work with double-slashes for FlexForm

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#252]
I am using the example for ["eval" => "Vendor ..."](https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Input/Properties/Eval.html), but using this in FlexForms

The string as specified in the example with double-slashes does not work in my example. String with single-slashes does, e.g.

not:
`'eval' => 'trim,Vendor\\Extension\\Evaluation\\ExampleEvaluation,required'`

but:
`'eval' => 'trim,Vendor\Extension\Evaluation\ExampleEvaluation,required'`

(However, as stated above this was tested with FlexForm, not with TCA directly)

**Comment by remonator** [comment]
Specifying the class name in `ext_localconf.php` as you did is also necessary when using without FlexForms (using 10.4.9).

**Comment by linawolf** [comment]
Can be found at https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Input/Properties/Eval.html now, Move Code to styleguide extension and make sure it is running.
