### ISSUE TITLE
Add clarification and possible values for subtypes_excludelist

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#263]
> “[field value]” => “[comma-separated list of fields (from the main types-config) which are removed]”
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Types/Index.html#subtypes-excludelist

https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Types/Index.html#subtypes-excludelist

For me, the explanation is a little vague. 

Also, a typical usecase - if used in Flexform - is to remove the record storage (pages) and recursive field (recursive). I don't know how I would be able to lookup this information. 

Values are (if used in Flexform), e.g.

* pages (record storage page)
* recursive 
* layout (?)
* select_key (?)

see also https://stackoverflow.com/questions/39386018/typo3-hide-plugin-mode-and-record-storage-page-in-a-plugin

**Comment by linawolf** [comment]
Has been stale for a year
