### ISSUE TITLE
Add a summary for MySql strict mode recommendations

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#269]
There are some things to consider, see also:

* https://forge.typo3.org/issues/88712
* https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/266
* https://stackoverflow.com/questions/40542151/typo3-sql-error-incorrect-integer-value-for-column-sys-language-uid-at

Where should we put this?

Suggestion: Add an "examples" section and add this there.

**Comment by linawolf** [comment]
there have already been merges
