### ISSUE TITLE
Changelog 10.4

### ISSUE THREAD

**Issue by maddy2101** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#273]
The 5-digit number is the forge issue number of the mentioned change

- [x] [Feature: 89573 - Allow flexible base url for slug fields in FormEngine](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-89573-AllowFlexibleBaseUrlForSlugFieldsInFormEngine.html)
  - https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Slug.html

- [x] 91008 select fields item grouping and sorting:
  - [Feature: 91008 - Item grouping for TCA select items](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91008-ItemGroupingForTCASelectItems.html)
  - [Feature: 91008 - Item sorting for TCA select items](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.4/Feature-91008-ItemSortingForTCASelectItems.html)

**Comment by linawolf** [comment]
This issue can be closed as soon as the open PRs are merged
