### ISSUE TITLE
Slugs with two path segments

### ISSUE THREAD

**Issue by bucheggerOnline** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#284]
Hi.

I'm wondering why the documentation says it's possible to use slugs with more than one path segment, but that leads always in an error like **Parameter "tx_database_database__product" for route "tx_database_database_0" must match "[^/]++" ("nr-000065/test-2016-city" given) to generate a corresponding URL.**

Is that a bug or is there a description missing how to use it properly?

I'm using T3V10.4.1

**Comment by linawolf** [comment]
I moved the examples into the styleguide extension, all of them are running. Your error must be something else.
