### ISSUE TITLE
Add code snippet example for itemsProcFunc

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#287]

**Comment by DavidBruchmann** [comment]
Here is a function referenced where available items are limited:
https://github.com/DavidBruchmann/wdb_news_snapin/blob/bc8871103119f1fbeeeecdbde44a62557a749a03/Configuration/TCA/tx_wdbnewssnapin_news_ttcontent_mm.php#L124

dont know if the reference shall be explained only or a running example itemsProcFunc shown too

**Comment by sypets** [comment]
@DavidBruchmann Thank you.

Currently](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Select.html#itemsprocfunc), you are just referred to the "styleguide" and there is no example at all. I thought about supplying a short example, both for defining the itemsProcFunc and for the function.

**Comment by DavidBruchmann** [comment]
yes, I felt that complaint already when I wrote my function ;-)
I will have a look.

**Comment by sypets** [comment]
Resolved with #288
