### ISSUE TITLE
type "group" internal_type file_reference warning: is this still necessary

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#310]
> file_reference
> This will create a field where files can be referenced. In contrast to “file”, referenced files (usually from fileadmin/) will not be copied to the upload folder. Warning: use this carefully. Your references will be broken if you delete referenced files in the filesystem!

Do we still want this warning? Shouldn't using references be encouraged instead?

https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Group.html#internal-type

**Comment by mbrodala** [comment]
Actually we should change the following hint to make it an actual warning:

> Types “file” and “file_reference” should not be used anymore. Use FAL references instead.

Right now it's a happy green block.

**Comment by DavidBruchmann** [comment]
> FAL references
should be linked then to the corresponding part of the documentation. Without link it's a bit out of context,

**Comment by sypets** [comment]
> Types “file” and “file_reference” should not be used anymore. Use FAL references instead.

Well, in the case of TCA columns type "group", it looks like "file" and "file_reference" are the only file options for internal_type. As options we only have file, file_reference, folder and db: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Group.html#internal-type

I had been operating under the assumption that `file_reference` means FAL. Probably it's a simple misunderstanding here, but would be great if the text clarified that and a link would also be great.

**Comment by mbrodala** [comment]
It probably is FAL but in a way too simplistic version. Real FAL integration means having an `inline` field instead ...

**Comment by sypets** [comment]
tt_content.assets uses "inline". Don't know why I started using "group", internal_type `file_reference`. Probably searched for it. And it works.

In that case, it might be a good idea to explain that and point to alternatives. 

_group_ looked like a good choice for files:

> The group element in TYPO3 makes it possible to create references to records from multiple tables in the system.

**Comment by sypets** [comment]
I am facing a deadline currently, and need some time to read both _inline_ and _groups_ pages to figure out what I would propose and if the documentation needs clarification. Or rather, to state it bluntly - am I the problem or is it the documentation?  Might be able to do that, but not right now. 

It seems to me though, this section could use some clarification.

**Comment by mbrodala** [comment]
I just had a closer look and these two options have been dropped with TYPO3v10 anyways:

- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5/Deprecation-86406-TCATypeGroupInternal_typeFileAndFile_reference.html
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

So the easiest and only correct solution would be removing these from the docs completely.

**Comment by susannemoog** [comment]
Accidentally fixed this issue while updating the docs to v10 - closing this one ;)

**Comment by sypets** [comment]
Yes, these "accidental" fixes are a real nuisance ;)
