### ISSUE TITLE
interface section is incomplete

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#340]
For example the TCA of the tt_content in the core has

`   
    'interface' => [
        'always_description' => 0,
    ],`

which is not  documented.

**Comment by brotkrueml** [comment]
At least `always_description` is gone in v12 with the removal of CSH: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97312-RemoveContextSensitiveHelp.html

**Comment by brotkrueml** [comment]
Addition: Link to the page in the manual: https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/Interface/Index.html

**Comment by brotkrueml** [comment]
Core uses the following keys for `interface` in v12:
- maxDBListItems
- maxSingleDBListItems
See: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/RecordList/DatabaseRecordList.php#L555-L566

The following are not used anymore and a TCA migration is in place (which removed them):
- showRecordFieldList
- always_description

So, I assume, the ticket can be closed, as only two keys are available in v12 for now (which are described).
