### ISSUE TITLE
Example not displayed for "exclude" page

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#347]
Example not displayed: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Columns/Properties/Exclude.html#example

There is a literalinclude in there: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/_sources/Columns/Properties/Exclude.rst.txt

**Comment by linawolf** [comment]
The example is displayed now.
