### ISSUE TITLE
type=inline: appearance missing property "createNewRelationLinkTitle"

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#350]
The type=inline documentation uses the appearance.createNewRelationLinkTitle property in an FAL example:
https://docs.typo3.org/m/typo3/reference-tca/8.7/en-us/ColumnsConfig/Type/Inline.html#file-abstraction-layer

But that "createNewRelationLinkTitle" property is not documented in the appearance property section:
- 10.4: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Inline.html#appearance
- master: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Inline/Properties/Appearance.html

**Comment by mbrodala** [comment]
You are right. Can you add this one?
