### ISSUE TITLE
"How to use the styleguide extension" shows up twice in the menu

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#364]
I don't know exactly what is the problem there, but it looks strange:

![image](https://user-images.githubusercontent.com/13206455/109885633-21853180-7c7f-11eb-9f85-c3e8b748fad8.png)

https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Examples/StyleGuide.html#styleguide

**Comment by marble** [comment]
What do you mean? The code markup in the headline?

    =====================================
    How to use the `styleguide` extension
    =====================================

**Comment by sypets** [comment]
The menu item "How to use the styleguide extension" exists twice in the menu (see screenshot above).
