### ISSUE TITLE
RTE chapter is missing some key points for beginners

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#387]
A colleague pointed me to https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Text/Index.html and hat troubles configurating an RTE for a text field.

Problems he had:
- The difference of the t3editor and the RTE
- To get an rte ` 'enableRichtext' => true` is needed but this is not documented here

**Comment by DavidBruchmann** [comment]
what's about this info?  
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Text/Default/Examples.html#rich-text-editor-field
