### ISSUE TITLE
Document new type "language"

### ISSUE THREAD

**Issue by nhovratov** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#414]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.2/Feature-57082-NewTCATypeLanguage.html

**Comment by linawolf** [comment]
It is documented here: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/Type/Language/Index.html
