### ISSUE TITLE
Image missing on rendered page "selectCheckBox"

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#421]
https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectCheckBox.html#columns-select-rendertype-selectcheckbox

![image](https://user-images.githubusercontent.com/13206455/126056858-2baab067-edd7-4a66-bf8e-9245c091d911.png)

Example
=======

```
.. figure:: ../../Images/TypeSelectStyleguideCheckbox7.png
   :alt: Select values from a checkbox list (select_checkbox_7)
   :class: with-shadow

   Select values from a checkbox list (select_checkbox_7)


.. code-block:: php

```

**Comment by DavidBruchmann** [comment]
#425

**Comment by mbrodala** [comment]
@DavidBruchmann Thanks for the pointer, this is fixed now.
