### ISSUE TITLE
Refine MM property

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#423]
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/CommonProperties/Mm.html

* property `MM` is supported by types `group` (`db`), `select` and `inline`
* type `group` only is supposed to support `allowed` (list of tables, comma separated)
* type `select` and `inline` are supposed to only support `foreign_table` (single table only)

**Comment by mbrodala** [comment]
Notice that `foreign_table` is mandatory if a `group` field should be used as Extbase domain model property. (Then `allowed` must be a single table.)

**Comment by ohader** [comment]
Please notice, that `allowed` is not supported at all in Extbase, it just supports the work-around `foreign_table`.
I guess this situation also lead to the fact, that there several places in the core that omitted `allowed` and just use `foreign_table`.

For this very issue in `type=group`, I think it makes sense to emphasize `allowed` the "real" property - and label `foreign_table` as work-around in addition(!) to `allowed`.

**Comment by mbrodala** [comment]
OK, that's already covered though: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Group.html#foreign-table

> This property does not really exist for group-type fields. It is needed as a workaround for an Extbase limitation. It is used to resolve dependencies during Extbase persistence. It should hold the same values as property allowed. Notice that only one table name is allowed here in contrast to the property allowed itself.

But I can see that it gets confusing if one focuses on `MM` only: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Group.html#mm

> Means that the relation to the records of foreign_table (or table specified in allowed property in case of the group field) is done with a M-M relation with a third “join” table.

**Comment by linawolf** [comment]
I believe this is covered in the newer vesions
