### ISSUE TITLE
Option "exclusiveKeys" only works for "selectMultipleSideBySide" / "selectTree"

### ISSUE THREAD

**Issue by mbrodala** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#426]
Currently the docs imply that the select option `exclusiveKeys` can be used for all render types. But this is not the case, only `selectMultipleSideBySide` and `selectTree` respect this option. All other render types do not change the selection if an exclusive key is selected. (And for `selectSingle` this would not even be possible.)

So this option should be extracted and displayed only for `selectMultipleSideBySide` / `selectTree`.

**Comment by nhovratov** [comment]
Well, the DataHandler checks only for `type="select"`, so it works kinda for all render types. But you are right, that the FormEngine only validates `selectMultipleSideBySide`  and `selectTree` / `category` in the backend forms.

We should make clear, that there is this distinction.
