### ISSUE TITLE
Field common property 'readOnly' is wrongly declared to be applicable only at check, flex, group, imageManipulation, input

### ISSUE THREAD

**Issue by LeoniePhiline** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#431]
Regarding https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/CommonProperties/ReadOnly.html#tca-property-readonly

The table shows an incomplete list of applicable field types:
> Types: check, flex, group, imageManipulation, input

However, `'readOnly'` can also be applied to e.g. `select`, `selectTree` or `radio` types; and maybe some others, too.

**Comment by nhovratov** [comment]
This is a general problem with most of the common properties. I'm currently working on an overview of all correct common properties and where they are available.

**Comment by nhovratov** [comment]
Hey, so this is a sheet I prepared: https://docs.google.com/spreadsheets/d/1T3w4i7ZnwmGQPy63A8ulOPzRTMrC3-gFK3H6SXRQOp0/edit?usp=sharing

The **first row** lists all the available **render types**. Note that a **type** can have multiple render types.
The **first column** shows the current common properties listed in the documentation plus some more I've found (not 100% complete).
The **green fields** show a match, meaning this property is used in the according render type.
I marked the **properties red**, which are falsely listed as a common property.
I marked the **properties green**, which are true common properties (used in all render types).
**Orange** are properties, which are common, but can have completely different configuration inside. For example appearance is a available in more than 1 render type, but the available array keys are not the same.

I got these informations by analyzing the source code. I don't claim 100% accuracy, but this is already much better and up to date what we currently have.
