### ISSUE TITLE
Description of TCA ctrl => type is easy to miss in properties overview - notation of array keys not consistent

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#451]
For the setting `$GLOBALS['TCA'][$table]['ctrl']['type']`, description overview "Record type" is used instead of "type". This was different in TYPO3 10.4 documentation. There, "type" was used as header. While this makes it more descriptive, I don't think this is a good change overall, because:

* "type" is the actual array key, it makes it easier to search for this
* the alphabetical sorting is broken (in the[ "table of content" for the properties](https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Ctrl/Properties/Index.html))
* It is inconsistent, e.g. for a number of other fields the array key is used (e.g. "tstamp" and not "timestamp") and not a descriptive term.

* **master**: overview page https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Ctrl/Properties/Index.html

![image](https://user-images.githubusercontent.com/13206455/135745353-b05a2e20-ac24-4641-9962-6ec704a041fd.png)

* **master**: detail page: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Ctrl/Properties/Type.html

* **10.4**: https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/Ctrl/

----

I kind of like the idea of using a descriptive **and** technical notation on the detail page https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Ctrl/Properties/Type.html

![image](https://user-images.githubusercontent.com/13206455/135745416-a5d363aa-1fa3-4d54-a816-557d2ca5a2f8.png)

but in that case it should be consistent for all properties and a solution should be found for the alphabetical TOC for the properties and making it easier to find a property if you know the technical representation.

----

I just noticed this problem when searching for the description of `ctrl => type`. When looking at the page https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Ctrl/Properties/Index.html I thought "type" was missing entirely at first glance.

---

See also issues #404 and #405 for similar observations about using technical notation vs. descriptive terms (or a combination of the two).

**Comment by linawolf** [comment]
Solved
