### ISSUE TITLE
IRRE: appearance.headerThumbnail property and code don't go together

### ISSUE THREAD

**Issue by julianhofmann** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#499]
The documentation tells `appearance.headerThumbnail` is a boolean defining "whether a thumbnail should be rendered in the inline elements’ header. This is used by the File Abstraction Layer to render a preview of the related image."

While having a look into the code in `\TYPO3\CMS\Backend\Form\Container\InlineRecordContainer`, the property `headerThumbnail`is expected to be an array having (among other things) a key 'file'.

I cannot decide which of them is correct (Also, because thumbnails apparently don't work apart from the FAL relation; see  https://forge.typo3.org/issues/96188 ). But it seems to me that the documentation and the code don't go together here.

**Comment by nhovratov** [comment]
Fixed in #503.
Can be closed.
