### ISSUE TITLE
type=imageManipulation missing

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#54]
https://wiki.typo3.org/TYPO3.CMS/Releases/7.2/Feature#Feature:_.2365585_-_Add_TCA_type_imageManipulation

**Comment by lolli42** [comment]
incoming

**Comment by cweiske** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/commit/7db6b58e974fb4d25bf4d00fe922532218a5cd3f
