### ISSUE TITLE
Property titles for page "type = ‘inline’" missing

### ISSUE THREAD

**Issue by simplychrislike** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#543]
I've also noticed that the property title 'appearance' is inside the left menu.
It seems like the problem only exists for the TYPO3 10.4 version of the page.

https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Inline.html

**Comment by linawolf** [comment]
solved (once page is rerendered)
