### ISSUE TITLE
Update searchable TCA types on v12 release

### ISSUE THREAD

**Issue by nhovratov** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#552]
In v12 many new TCA types will be added and with this the searchable TCA types will change.

#551

**Comment by linawolf** [comment]
the related PR is merged, can this be closed?

**Comment by linawolf** [comment]
They will all have changelog entries, those get automatically listed here: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624

**Comment by nhovratov** [comment]
These are not single patches, but included in all new introduced TCA types.

**Comment by nhovratov** [comment]
I will take care of it.
