### ISSUE TITLE
Add description to selectTree

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#664]
> A field with the render type selectTree displays hierarchical data in a tree.

https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Select/Tree/Index.html#columns-select-rendertype-selecttree

Doesn't have to be long, maybe a description which makes it clear

* that "hierarchical data" must use a table from the database.
* Also, which are the required fields (I think at least treeConfig, foreign_table).
* Items or itemsProcFunc is optional but not sufficient to pass values.
* top item will always be the "descriptive" name of the table
* can you join several tables?

**Comment by linawolf** [comment]
@FlorianT03 can you help here?
