### ISSUE TITLE
For inline field type maxitems and minitems are not listed as properties

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#677]
https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Inline/Index.html

but these values are possible and can be used.

**Comment by nhovratov** [comment]
They are listed under `common properties` I think that's why they are not in the navigation.

**Comment by sypets** [comment]
So, is this a "user error" on my part? I am not sufficiently familiar with the current structure. 

Also, it is a little confusing that maxitems and minitems is listed for selectTree under "common properties", see https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/ColumnsConfig/Type/Select/Tree/Properties.html, but not for the inline field.

**Comment by linawolf** [comment]
I have improved the listing it should be more clear now
