### ISSUE TITLE
Sentence inside ColumnsConfig/Type/User/Index.rst is cut off

### ISSUE THREAD

**Issue by PKuhlmay** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#725]
It seems that there are some information missing. The last sentence is "Additional render types". For me, it seems that there is missing something inside this sentence.

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/blob/dd1e72fd1ab290d55fb7ac621ded1e404b9b50b9/Documentation/ColumnsConfig/Type/User/Index.rst?plain=1#L205

**Comment by linawolf** [comment]
@FlorianT03 could you have a look please?
