### ISSUE TITLE
Missing "previewRenderer" documentation

### ISSUE THREAD

**Issue by sfroemkenjw** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#781]
### Current behavior

The "previewRenderer" property is missing here:
https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/Ctrl/Properties/Index.html
https://docs.typo3.org/m/typo3/reference-tca/11.5/en-us/Types/Properties/Index.html

### Expected behavior/output

I expect a documentation in general.
Seems that string and array is allowed here. Would be cool to have 1 or 2 examples here.

### Links

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-78450-IntroducePreviewRendererPattern.html

### TYPO3 versions

All docs are missing this property since TYPO3 10.3

**Comment by brotkrueml** [comment]
Creating a custom preview renderer is documented in TYPO3 Explained:
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/ContentElements/CustomBackendPreview.html

But you are right, this is missing in the TCA docs.
