### ISSUE TITLE
Show all default values

### ISSUE THREAD

**Issue by pfeiferbit** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#81]
One of my biggest problems when working on a TYPO3 extension is that I do not know what the default values are for configuration options. It would be a tremendous help to see them _everywhere_. And that's not limited to the TCA ref.

When I'm having some spare time I will make a pull request intended as a proposal.

**Comment by marble** [comment]
I'm looking forward to that! And I can sense the same pain you're feeling. If there would be a miraculous solution I would go for it. But I'm afraid we can only go the "stony" was. But sometimes, I think, just adding a link could give a lot of insight, like pointing to https://git.typo3.org/Packages/TYPO3.CMS.git/blob/HEAD:/typo3/sysext/core/Configuration/DefaultConfiguration.php

**Comment by DavidBruchmann** [comment]
Sometimes I think better or additional examples would help a lot too.
Many examples are take from core but in extensions the logic is working from the extensions-directory and the core-examples are not useless but still difficult to implement. So taking examples from extensions in typo3conf/ext/ can help a lot.

**Comment by marble** [comment]
Yes, I'm a fan of detailed and elaborated examples too. And they should contain not too little context so they can be understood by themself.
