### ISSUE TITLE
Suggest wizard misses addWhere docs

### ISSUE THREAD

**Issue by lolli42** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#83]
It is possible to define "addWhere" for suggest wizards, this property is only documented for pageTS, but is also possible as direct TCA config:

Task: Test and play around with this TCA setting and document it.

tca reference of suggest wizard:
https://docs.typo3.org/typo3cms/TCAReference/AdditionalFeatures/WizardsConfiguration/Index.html#suggest-wizards

page ts config docs of addWhere:
https://docs.typo3.org/typo3cms/TSconfigReference/PageTsconfig/TCEform/Index.html  (search "addWhere")

**Comment by liayn** [comment]
I thought I documented that recently...

**Comment by marble** [comment]
'addWhere' only appears here it seems. Is it a hit? I didn't read ...
https://docs.typo3.org/typo3cms/TSconfigReference/search.html?q=addwher&check_keywords=yes&area=default

**Comment by lolli42** [comment]
uhm yes ... as said. it IS documented in ts config ref, but NOT in TCA ref. and as far as I can see, it works in TCA, too (reading the code).

**Comment by lolli42** [comment]
this has been added to the docs.
