### ISSUE TITLE
shadowColumnsForMovePlaceholders referencing non existing value

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Reference-TCA#84]
In the 
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/blob/latest/Documentation/Reference/Ctrl/Index.rst#shadowcolumnsformoveplaceholders
there is a sentence:
```
Move placeholders are used only when property :ref:`versioningWS <ctrl-reference-versioningws>` is set to 2 (instead of 1 or TRUE).
```
however since https://review.typo3.org/#/c/50462/8  `versioningWS` is a bolean value.
Not sure whether we should remove the sentence, or change it's meaning.

**Comment by liayn** [comment]
To my understanding placeholders are always generated now. But @ohader can shed some light on that maybe?

**Comment by ohader** [comment]
Move-placeholders are used per default since TYPO3 7.6.0 if `versioningWS` is enabled (any value that casts to `true`). This change has been introduced with https://review.typo3.org/35685. Thus, the documentation has to be extended like "Since TYPO3 CMS 7 LTS move-placeholders are always used."

**Comment by tmotyl** [comment]
thanks! on my way to create a pull request :)
